### ISSUE TITLE
Allow for Array of Object support

### ISSUE THREAD

**Issue by apetitbois** [a-h/generate#6] opened 2016-11-28 16:25 UTC
Hi,

Thanks for solving issue #4.

While looking at my schemas, I encountered another issue.
If I use arrays of objects (which I do), they are not properly referenced and only one of them is actually created (under the name ***Root*** and referenced as ***[]object***).

See schema below :
```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "physical_server.json",
  "description": "Physical Server asset",
  "type": "object",
  "properties": {
    "id": {
      "description": "BSON ID",
      "type": "string"
    },
    "notes": {
      "type": "string"
    },
    "type": {
      "type": "string",
      "description": "Type of asset this represents",
      "pattern": "^physical_server$"
    },
    "created": {
      "type": "string"
    },
    "updated": {
      "type": "string"
    },
    "deleted": {
      "type": "string"
    },
    "attributes": {
      "type": "object",
      "description": "Specific attributes of the asset",
      "properties": {
        "hostname": {
          "type": "string"
        },
        "environments": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "operating_system": {
          "type": "object",
          "description": "Running operating system",
          "properties": {
            "family": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "version": {
              "type": "string"
            },
            "revision": {
              "type": "string"
            }
          }
        },
        "disk": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "brand":{"type":"string"},
              "size":{"type":"number"},
              "type":{"type":"string"}
            }
          }
        },
        "location": {
          "type": "string",
          "description": "Physical location of this server (datacenter, rack, pod, etc)"
        },
        "serial_number": {
          "type": "string"
        }
      }
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "asset_id": {
            "type": "string"
          },
          "relationship": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        }
      }
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}
```

Here is the output I get : 
```go
package main

type Attributes struct {
  Disk []object `json:"disk,omitempty"`
  Environments []string `json:"environments,omitempty"`
  Hostname string `json:"hostname,omitempty"`
  Location string `json:"location,omitempty"`
  Operatingsystem *Operatingsystem `json:"operating_system,omitempty"`
  Serialnumber string `json:"serial_number,omitempty"`
}

type Operatingsystem struct {
  Family string `json:"family,omitempty"`
  Name string `json:"name,omitempty"`
  Revision string `json:"revision,omitempty"`
  Version string `json:"version,omitempty"`
}

type Physicalserver.json struct {
  Attributes *Attributes `json:"attributes,omitempty"`
  Created string `json:"created,omitempty"`
  Deleted string `json:"deleted,omitempty"`
  Id string `json:"id,omitempty"`
  Links []object `json:"links,omitempty"`
  Notes string `json:"notes,omitempty"`
  Tags []string `json:"tags,omitempty"`
  Type string `json:"type,omitempty"`
  Updated string `json:"updated,omitempty"`
}

type Root struct {
  Brand string `json:"brand,omitempty"`
  Size float64 `json:"size,omitempty"`
  Type string `json:"type,omitempty"`
}
```

**Comment by a-h** [comment] 2016-11-29 19:36
Thanks, I'd only done enough on this library to make it work for my limited use case after I found that other libraries just plain didn't work, so I thought I should make the effort to try and get this working. :joy: 

I've added another pull request which should do the job for this, it will generate:

```bash
go run ./cmd/schema-generate/main.go -i ./cmd/issue6.json
```

```go
package main

type Attributes struct {
  Hostname string `json:"hostname,omitempty"`
  Location string `json:"location,omitempty"`
  OperatingSystem *OperatingSystem `json:"operating_system,omitempty"`
  SerialNumber string `json:"serial_number,omitempty"`
}

type Links struct {
  AssetId string `json:"asset_id,omitempty"`
  Description string `json:"description,omitempty"`
  Relationship string `json:"relationship,omitempty"`
}

type OperatingSystem struct {
  Family string `json:"family,omitempty"`
  Name string `json:"name,omitempty"`
  Revision string `json:"revision,omitempty"`
  Version string `json:"version,omitempty"`
}

type PhysicalServerAsset struct {
  Attributes *Attributes `json:"attributes,omitempty"`
  Links []Links `json:"links,omitempty"`
  Tags []string `json:"tags,omitempty"`
}
```

I thought that the code should try and do a better job of avoiding the "Root" name, so it tries a few things. I've fixed up the casing so that `computer_repair` becomes `ComputerRepair` not `Computerrepair` as it was before.

I've also dotted a few more comments around, it's been a while since I've used JSON schema or looked at this code!

What do you think?

Also, I hope you don't mind, but I've checked in your example as `issue6.json` with the idea of maybe making a regression suite of files to add to the unit tests.

**Comment by apetitbois** [comment] 2016-11-30 16:43
It works great !
I can safely say that you support all my use cases, which covers a lot of the schema already.

Thanks a lot.

**Closed** 2016-12-01 08:31 UTC
